import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Next 내장 Google 폰트인 Inter를 사용하여 빌드 시 폰트 미인식 오류(Geist) 문제를 회피합니다.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
