import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Next 기본 제공 폰트 Inter로 교체하여 미지원 폰트(Geist)로 인한 컴파일 오류를 방지합니다.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
